library(nicholsonppp)
sim <- simulate.drift.selection()
df <- sim2df(sim)
loci.over.time(subset(df,locus<10),pop.colors=c('black','grey','white'))
loci.over.time(subset(df,locus==1))
anc.est.plot(subset(df,generation==generations),1)
fixation.endpoints(subset(df,generation==generations),hilite.locus=1)
bigplot(df)
evolution.animation("newtest3","Allele frequency and ancestral estimate evolution",df)
