source("../R/sim.R")
source("../R/plot.R")
source("../R/model.R")
dyn.load("../src/0mers_twist.so")
sim <- sim.drift.selection(generations=200,s=0.05,loci=100)
df <- sim2df(sim)
res20 <- sapply((1:20)*10,function(g)nicholsonppp(sim$sim[,,g]),simplify=FALSE)
##load("c.Rdata")
save.image("allc.Rdata")
library(ggplot2)
cc <- melt(sapply(res4,function(L)L$c))
names(cc) <- c("population","generation","c.est")
cc$generation <- cc$generation*25
qplot(generation,c.est,data=cc,group=population,geom="line")
